version: "3"

services:
    
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - api
            - client
        restart: always
        ports:
            - "3080:80"

    api:
        image: jamm3e3333/react-anthony-app_api
        build:
            dockerfile: Dockerfile
            context: ./express-server
        

    client:
        image: jamm3e3333/react-anthony-app_client
        stdin_open: true
        build: 
            dockerfile: Dockerfile
            context: ./monitor-parking
