version: "3"

services: 

    api:
        volumes:
            - /app/node_modules
            - ./express-server:/app
        env_file: 
            - ./express-server/config/dev.env
        command: npm run dev

    client:
        volumes:
            - ./monitor-parking:/app